# -*- coding: utf-8 -*-
"""Uber data analysiis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lMB_XuMqCa4T86a5F0dM_GMOHNCsVlhA

# ***Uber Data Analysis***
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv("/content/uber-raw-data-sep14.csv")
data["Date/Time"] = data["Date/Time"].map(pd.to_datetime)
data.head()

data["Day"] = data["Date/Time"].apply(lambda x: x.day)
data["Weekday"] = data["Date/Time"].apply(lambda x: x.weekday())
data["Hour"] = data["Date/Time"].apply(lambda x: x.hour)
print(data.head())

"""So I have prepared this data according to the days and hours, as I am using the Uber trips for the September month so let’s have a look at each day to see on which day the Uber trips were highest:"""

sns.set(rc={'figure.figsize':(12, 10)})
sns.distplot(data["Day"])

"""By looking at the daily trips we can say that the Uber trips are rising on the working days and decreases on the weekends. Now let’s analyze the Uber trips according to the hours:"""

sns.distplot(data["Hour"])

"""According to the hourly data, the Uber trips decreases after midnight and then start increasing after 5 am and the trips keep rising till 6 pm such that 6 pm is the busiest hour for Uber then the trips start decreasing. Now let’s analyze the Uber trips according to the weekdays:"""

sns.distplot(data["Weekday"])

"""In the above figure 0 indicates Sunday, on Sundays the Uber trips and more than Saturdays so we can say people also use Uber for outings rather than for just going to work. On Saturdays, the Uber trips are the lowest and on Mondays, they are the highest. Now let’s have a look at the correlation of hours and weekdays on the Uber trips:"""

# Correlation of Weekday and Hour
df = data.groupby(["Weekday", "Hour"]).apply(lambda x: len(x))
df = df.unstack()
sns.heatmap(df, annot=False)

"""As we are having the data about longitude and latitude so we can also plot the density of Uber trips according to the regions of the New Your city:"""

data.plot(kind='scatter', x='Lon', y='Lat', alpha=0.4, s=data['Day'], label='Uber Trips',
figsize=(12, 8), cmap=plt.get_cmap('jet'))
plt.title("Uber Trips Analysis")
plt.legend()
plt.show()

"""Summary
So this is how we can analyze the Uber trips for New York City. Some of the conclusions that I got from this analysis are:


*   Monday is the most profitable day for Uber
*   On Saturdays less number of people use Uber
*   6 pm is the busiest day for Uber
*   On average a rise in Uber trips start around 5 am.
*   Most of the Uber trips originate near the Manhattan region in New York.









"""